version: "3.9"

services:
   service1:
    image: service11
    build: 
       context: ./service-1
    ports:
      - "5001:5001"
    networks:
      - my_network
    depends_on:
      - rabbitmq

   service2:
    image: service22
    build:
      context: ./service-2
    ports:
      - "5002:5002"
    networks:
      - my_network
    depends_on:
     - rabbitmq

   rabbitmq:
    image: rabbitmq:latest
    ports:
      - "5672:5672"
    networks:
      - my_network

networks:
  my_network:
